"""
100 DAYS OF AI/ML ROADMAP
Every day has: Topic, Video Link, Notes Link, Practice Link
ALL RESOURCES ARE 100% FREE
"""


def get_full_roadmap():
    roadmap = {
        # ========== PHASE 1: PYTHON (Days 1-12) ==========
        1: {
            "day": 1,
            "phase": "PYTHON",
            "phase_color": "#4CAF50",
            "topic": "Python Setup + Variables + Data Types + Input/Output",
            "video_title": "Python Full Course for Beginners (0:00 - 1:10:00)",
            "video_url": "https://www.youtube.com/watch?v=rfscVS0vtbw",
            "video_title2": "Python Variables & Data Types - Corey Schafer",
            "video_url2": "https://www.youtube.com/watch?v=khKv-8q7YmY",
            "notes_url": "https://www.w3schools.com/python/python_variables.asp",
            "notes_title": "W3Schools - Python Variables & Data Types",
            "practice_url": "https://www.hackerrank.com/domains/python",
            "practice_title": "HackerRank Python Practice",
            "pdf_url": "https://www.geeksforgeeks.org/python-programming-language-tutorial/",
            "pdf_title": "GFG - Python Complete Tutorial",
            "tasks": [
                "Install Python + Setup Google Colab",
                "Learn variables, data types (int, float, str, bool)",
                "Learn input() and print()",
                "Write 25 small programs",
            ],
        },
        2: {
            "day": 2,
            "phase": "PYTHON",
            "phase_color": "#4CAF50",
            "topic": "Strings + String Methods + String Formatting",
            "video_title": "Python Strings Tutorial - Corey Schafer",
            "video_url": "https://www.youtube.com/watch?v=k9TUPpGqYTo",
            "video_title2": "String Formatting - Corey Schafer",
            "video_url2": "https://www.youtube.com/watch?v=vTX3IwquFkc",
            "notes_url": "https://www.w3schools.com/python/python_strings.asp",
            "notes_title": "W3Schools - Python Strings",
            "practice_url": "https://www.hackerrank.com/challenges/python-string-split-and-join",
            "practice_title": "HackerRank String Challenges",
            "pdf_url": "https://www.geeksforgeeks.org/python-string/",
            "pdf_title": "GFG - Python Strings Complete Guide",
            "tasks": [
                "String slicing and indexing",
                "String methods (upper, lower, split, join, replace)",
                "f-strings and .format()",
                "20 string exercises",
            ],
        },
        3: {
            "day": 3,
            "phase": "PYTHON",
            "phase_color": "#4CAF50",
            "topic": "Lists + Tuples + Sets",
            "video_title": "Python Lists Tutorial - Corey Schafer",
            "video_url": "https://www.youtube.com/watch?v=W8KRzm-HUcc",
            "video_title2": "Python Tuples and Sets - Corey Schafer",
            "video_url2": "https://www.youtube.com/watch?v=Mf7eFtbVxFM",
            "notes_url": "https://www.w3schools.com/python/python_lists.asp",
            "notes_title": "W3Schools - Python Lists",
            "practice_url": "https://www.hackerrank.com/challenges/python-lists",
            "practice_title": "HackerRank List Problems",
            "pdf_url": "https://www.geeksforgeeks.org/python-lists/",
            "pdf_title": "GFG - Python Lists Complete Guide",
            "tasks": [
                "List operations (append, extend, insert, remove)",
                "List slicing and comprehensions",
                "Tuples (immutable) and Sets (unique)",
                "20 list problems",
            ],
        },
        4: {
            "day": 4,
            "phase": "PYTHON",
            "phase_color": "#4CAF50",
            "topic": "Dictionaries + Loops (for/while)",
            "video_title": "Python Dictionaries - Corey Schafer",
            "video_url": "https://www.youtube.com/watch?v=daefaLgNkw0",
            "video_title2": "Python Loops - Corey Schafer",
            "video_url2": "https://www.youtube.com/watch?v=6iF8Xb7Z3wQ",
            "notes_url": "https://www.w3schools.com/python/python_dictionaries.asp",
            "notes_title": "W3Schools - Dictionaries & Loops",
            "practice_url": "https://www.hackerrank.com/challenges/python-loops",
            "practice_title": "HackerRank Loop Challenges",
            "pdf_url": "https://www.geeksforgeeks.org/python-dictionary/",
            "pdf_title": "GFG - Python Dictionaries",
            "tasks": [
                "Dictionary CRUD operations",
                "Nested dictionaries",
                "for loops, while loops, break, continue",
                "Build a Contact Book program",
            ],
        },
        5: {
            "day": 5,
            "phase": "PYTHON",
            "phase_color": "#4CAF50",
            "topic": "Functions + Lambda + Map/Filter/Zip",
            "video_title": "Python Functions - Corey Schafer",
            "video_url": "https://www.youtube.com/watch?v=9Os0o3wzS_I",
            "video_title2": "First Class Functions + Closures",
            "video_url2": "https://www.youtube.com/watch?v=kr0mpwqttM0",
            "notes_url": "https://www.w3schools.com/python/python_functions.asp",
            "notes_title": "W3Schools - Python Functions",
            "practice_url": "https://www.hackerrank.com/challenges/write-a-function",
            "practice_title": "HackerRank Function Challenges",
            "pdf_url": "https://www.geeksforgeeks.org/python-functions/",
            "pdf_title": "GFG - Python Functions",
            "tasks": [
                "Define functions with args, kwargs",
                "Return values, default params",
                "Lambda, map(), filter(), zip()",
                "Write 20 functions",
            ],
        },
        6: {
            "day": 6,
            "phase": "PYTHON",
            "phase_color": "#4CAF50",
            "topic": "File Handling + Exception Handling",
            "video_title": "File Handling - Corey Schafer",
            "video_url": "https://www.youtube.com/watch?v=Uh2ebFW8OYM",
            "video_title2": "Error Handling Try/Except - Corey Schafer",
            "video_url2": "https://www.youtube.com/watch?v=NIWwJbo-9_8",
            "notes_url": "https://www.w3schools.com/python/python_file_handling.asp",
            "notes_title": "W3Schools - File Handling",
            "practice_url": "https://www.hackerrank.com/challenges/python-exceptions",
            "practice_title": "HackerRank Exception Challenges",
            "pdf_url": "https://www.geeksforgeeks.org/file-handling-python/",
            "pdf_title": "GFG - File Handling in Python",
            "tasks": [
                "Read/Write text and CSV files",
                "try, except, finally, raise",
                "Custom exceptions",
                "Build a file-based To-Do app",
            ],
        },
        7: {
            "day": 7,
            "phase": "PYTHON",
            "phase_color": "#4CAF50",
            "topic": "OOP: Classes + Objects + __init__",
            "video_title": "Python OOP 1 - Classes & Instances",
            "video_url": "https://www.youtube.com/watch?v=ZDa-Z5JzLYM",
            "video_title2": "Python OOP 2 - Class Variables",
            "video_url2": "https://www.youtube.com/watch?v=BJ-VvGyQxho",
            "notes_url": "https://www.w3schools.com/python/python_classes.asp",
            "notes_title": "W3Schools - Python OOP",
            "practice_url": "https://www.hackerrank.com/challenges/class-1-dealing-with-complex-numbers",
            "practice_title": "HackerRank OOP Challenges",
            "pdf_url": "https://www.geeksforgeeks.org/python-oops-concepts/",
            "pdf_title": "GFG - Python OOP Complete",
            "tasks": [
                "Create classes with __init__",
                "Instance vs class variables",
                "Methods and self",
                "Build Student & BankAccount classes",
            ],
        },
        8: {
            "day": 8,
            "phase": "PYTHON",
            "phase_color": "#4CAF50",
            "topic": "OOP: Inheritance + Polymorphism + Dunder Methods",
            "video_title": "Python OOP 3 - Inheritance",
            "video_url": "https://www.youtube.com/watch?v=RSl87lqOXDE",
            "video_title2": "Python OOP 4 - Special Methods (Dunder)",
            "video_url2": "https://www.youtube.com/watch?v=3ohzBxoFHAY",
            "notes_url": "https://www.w3schools.com/python/python_inheritance.asp",
            "notes_title": "W3Schools - Inheritance",
            "practice_url": "https://www.hackerrank.com/challenges/class-2-find-the-torsional-angle",
            "practice_title": "HackerRank OOP Practice",
            "pdf_url": "https://www.geeksforgeeks.org/inheritance-in-python/",
            "pdf_title": "GFG - Python Inheritance",
            "tasks": [
                "Single & multiple inheritance",
                "Method overriding, super()",
                "__str__, __repr__, __len__",
                "Build Shape > Circle > Sphere hierarchy",
            ],
        },
        9: {
            "day": 9,
            "phase": "PYTHON",
            "phase_color": "#4CAF50",
            "topic": "List Comprehensions + Generators + Decorators",
            "video_title": "Comprehensions - Corey Schafer",
            "video_url": "https://www.youtube.com/watch?v=3dt4OGnU5sM",
            "video_title2": "Generators + Decorators - Corey Schafer",
            "video_url2": "https://www.youtube.com/watch?v=bD05uGo_sVI",
            "notes_url": "https://www.w3schools.com/python/python_lists_comprehension.asp",
            "notes_title": "W3Schools - Comprehensions",
            "practice_url": "https://www.hackerrank.com/challenges/list-comprehensions",
            "practice_title": "HackerRank Comprehension Practice",
            "pdf_url": "https://www.geeksforgeeks.org/python-list-comprehension/",
            "pdf_title": "GFG - Comprehensions & Generators",
            "tasks": [
                "List, dict, set comprehensions",
                "Generator functions with yield",
                "Decorators with @syntax",
                "15 comprehension exercises",
            ],
        },
        10: {
            "day": 10,
            "phase": "PYTHON",
            "phase_color": "#4CAF50",
            "topic": "Intermediate Python: args/kwargs + Collections",
            "video_title": "Intermediate Python (0:00 - 2:30:00)",
            "video_url": "https://www.youtube.com/watch?v=HGOBQPFzWKo",
            "video_title2": "Python *args **kwargs - Corey Schafer",
            "video_url2": "https://www.youtube.com/watch?v=c0x5gRXG8Rc",
            "notes_url": "https://www.geeksforgeeks.org/args-kwargs-python/",
            "notes_title": "GFG - args and kwargs",
            "practice_url": "https://www.hackerrank.com/domains/python",
            "practice_title": "HackerRank Python Medium",
            "pdf_url": "https://www.geeksforgeeks.org/python-collections-module/",
            "pdf_title": "GFG - Collections Module",
            "tasks": [
                "*args and **kwargs",
                "Collections: Counter, defaultdict, namedtuple",
                "Itertools basics",
                "Advanced exercises",
            ],
        },
        11: {
            "day": 11,
            "phase": "PYTHON",
            "phase_color": "#4CAF50",
            "topic": "Intermediate Python: RegEx + JSON + OS Module",
            "video_title": "Intermediate Python (2:30:00 - 5:00:00)",
            "video_url": "https://www.youtube.com/watch?v=HGOBQPFzWKo",
            "video_title2": "Regular Expressions - Corey Schafer",
            "video_url2": "https://www.youtube.com/watch?v=K8L6KVGG-7o",
            "notes_url": "https://www.w3schools.com/python/python_regex.asp",
            "notes_title": "W3Schools - Python RegEx",
            "practice_url": "https://regexone.com/",
            "practice_title": "RegexOne Interactive Practice",
            "pdf_url": "https://www.geeksforgeeks.org/python-regex/",
            "pdf_title": "GFG - Python RegEx Complete",
            "tasks": [
                "Regular expressions patterns",
                "JSON reading and writing",
                "OS module for file operations",
                "Text parsing exercises",
            ],
        },
        12: {
            "day": 12,
            "phase": "PYTHON",
            "phase_color": "#4CAF50",
            "topic": "PYTHON PROJECT DAY + GitHub Setup",
            "video_title": "Git & GitHub Crash Course - Traversy Media",
            "video_url": "https://www.youtube.com/watch?v=SWYqp7iY_Tc",
            "video_title2": "Python Projects for Beginners",
            "video_url2": "https://www.youtube.com/watch?v=8ext9G7xspg",
            "notes_url": "https://docs.github.com/en/get-started/quickstart",
            "notes_title": "GitHub Official Quickstart Guide",
            "practice_url": "https://github.com/",
            "practice_title": "Create Your GitHub Account",
            "pdf_url": "https://www.geeksforgeeks.org/python-projects-beginner-to-advanced/",
            "pdf_title": "GFG - Python Project Ideas",
            "tasks": [
                "Setup GitHub account",
                "Learn git add, commit, push",
                "Build Quiz Game or Expense Tracker",
                "Push project to GitHub",
            ],
        },

        # ========== PHASE 2: MATH FOR ML (Days 13-17) ==========
        13: {
            "day": 13,
            "phase": "MATH",
            "phase_color": "#FF9800",
            "topic": "Linear Algebra: Vectors, Matrices, Transformations",
            "video_title": "Essence of Linear Algebra (FULL PLAYLIST)",
            "video_url": "https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab",
            "video_title2": "Linear Algebra for ML - StatQuest",
            "video_url2": "https://www.youtube.com/watch?v=fNk_zzaMoSs",
            "notes_url": "https://mml-book.github.io/book/mml-book.pdf",
            "notes_title": "Mathematics for ML Book (FREE PDF)",
            "practice_url": "https://www.khanacademy.org/math/linear-algebra",
            "practice_title": "Khan Academy - Linear Algebra",
            "pdf_url": "https://cs229.stanford.edu/section/cs229-linalg.pdf",
            "pdf_title": "Stanford CS229 Linear Algebra Notes (PDF)",
            "tasks": [
                "Watch ALL 3Blue1Brown Linear Algebra videos",
                "Vectors, dot product, cross product",
                "Matrix multiplication, transpose, inverse",
                "Eigenvalues and eigenvectors",
            ],
        },
        14: {
            "day": 14,
            "phase": "MATH",
            "phase_color": "#FF9800",
            "topic": "Calculus: Derivatives, Gradients, Chain Rule",
            "video_title": "Essence of Calculus (KEY CHAPTERS 1-6)",
            "video_url": "https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr",
            "video_title2": "Gradient Descent - 3Blue1Brown",
            "video_url2": "https://www.youtube.com/watch?v=IHZwWFHWa-w",
            "notes_url": "https://mml-book.github.io/book/mml-book.pdf",
            "notes_title": "MML Book - Chapter 5 (Calculus)",
            "practice_url": "https://www.khanacademy.org/math/calculus-1",
            "practice_title": "Khan Academy - Calculus",
            "pdf_url": "https://cs229.stanford.edu/section/cs229-linalg.pdf",
            "pdf_title": "Stanford CS229 Math Notes",
            "tasks": [
                "Derivatives and partial derivatives",
                "Chain rule (crucial for backprop!)",
                "Gradient vectors",
                "Implement gradient descent from scratch",
            ],
        },
        15: {
            "day": 15,
            "phase": "MATH",
            "phase_color": "#FF9800",
            "topic": "Probability: Bayes Theorem, Conditional Probability",
            "video_title": "Bayes Theorem - 3Blue1Brown",
            "video_url": "https://www.youtube.com/watch?v=HZGCoVF3YvM",
            "video_title2": "Probability Explained - StatQuest",
            "video_url2": "https://www.youtube.com/watch?v=uzkc-qNVoOk",
            "notes_url": "https://www.khanacademy.org/math/statistics-probability/probability-library",
            "notes_title": "Khan Academy - Probability",
            "practice_url": "https://www.khanacademy.org/math/statistics-probability",
            "practice_title": "Khan Academy Practice Problems",
            "pdf_url": "https://cs229.stanford.edu/section/cs229-prob.pdf",
            "pdf_title": "Stanford CS229 Probability Notes (PDF)",
            "tasks": [
                "Basic probability rules",
                "Conditional probability",
                "Bayes theorem (very important for ML!)",
                "Solve 20 probability problems",
            ],
        },
        16: {
            "day": 16,
            "phase": "MATH",
            "phase_color": "#FF9800",
            "topic": "Statistics: Distributions, Hypothesis Testing",
            "video_title": "Statistics Fundamentals - StatQuest",
            "video_url": "https://www.youtube.com/playlist?list=PLblh5JKOoLUK0FLuzwntyYI10UQFUhsY9",
            "video_title2": "Normal Distribution - StatQuest",
            "video_url2": "https://www.youtube.com/watch?v=rzFX5NWojp0",
            "notes_url": "https://www.khanacademy.org/math/statistics-probability",
            "notes_title": "Khan Academy - Statistics",
            "practice_url": "https://www.khanacademy.org/math/statistics-probability",
            "practice_title": "Khan Academy Stats Practice",
            "pdf_url": "https://www.geeksforgeeks.org/statistics-for-machine-learning/",
            "pdf_title": "GFG - Statistics for ML",
            "tasks": [
                "Mean, median, mode, variance, std deviation",
                "Normal/Gaussian distribution",
                "Correlation and covariance",
                "Calculate statistics in Python",
            ],
        },
        17: {
            "day": 17,
            "phase": "MATH",
            "phase_color": "#FF9800",
            "topic": "Information Theory + Math Revision",
            "video_title": "Entropy - StatQuest",
            "video_url": "https://www.youtube.com/watch?v=YtebGVx-Fxw",
            "video_title2": "Cross-Entropy - StatQuest",
            "video_url2": "https://www.youtube.com/watch?v=6ArSys5qHAU",
            "notes_url": "https://www.geeksforgeeks.org/entropy-information-gain-machine-learning/",
            "notes_title": "GFG - Entropy & Information Gain",
            "practice_url": "https://www.khanacademy.org/math/statistics-probability",
            "practice_title": "Revise all math topics",
            "pdf_url": "https://mml-book.github.io/book/mml-book.pdf",
            "pdf_title": "MML Book Complete (FREE PDF)",
            "tasks": [
                "Entropy and cross-entropy",
                "KL Divergence",
                "Revise all math concepts",
                "Implement entropy in Python",
            ],
        },

        # ========== PHASE 3: DATA SCIENCE (Days 18-27) ==========
        18: {
            "day": 18,
            "phase": "DATA SCIENCE",
            "phase_color": "#2196F3",
            "topic": "NumPy: Arrays, Indexing, Slicing, Reshaping",
            "video_title": "Complete NumPy Tutorial - Keith Galli",
            "video_url": "https://www.youtube.com/watch?v=GB9ByFAIAH4",
            "video_title2": "NumPy Tutorial - FreeCodeCamp",
            "video_url2": "https://www.youtube.com/watch?v=QUT1VHiLmmI",
            "notes_url": "https://numpy.org/doc/stable/user/quickstart.html",
            "notes_title": "NumPy Official Quickstart",
            "practice_url": "https://www.kaggle.com/learn/intro-to-machine-learning",
            "practice_title": "Kaggle - Start ML Journey",
            "pdf_url": "https://www.w3schools.com/python/numpy/default.asp",
            "pdf_title": "W3Schools - NumPy Tutorial",
            "tasks": [
                "Create arrays (1D, 2D, 3D)",
                "Indexing, slicing, reshaping",
                "Array operations and broadcasting",
                "30 NumPy exercises",
            ],
        },
        19: {
            "day": 19,
            "phase": "DATA SCIENCE",
            "phase_color": "#2196F3",
            "topic": "NumPy Advanced: Math Ops, Linear Algebra, Random",
            "video_title": "Data Analysis with Python (0:00-2:00)",
            "video_url": "https://www.youtube.com/watch?v=r-uOLxNrNk8",
            "video_title2": "NumPy for Data Science",
            "video_url2": "https://www.youtube.com/watch?v=GB9ByFAIAH4",
            "notes_url": "https://numpy.org/doc/stable/reference/routines.linalg.html",
            "notes_title": "NumPy Linear Algebra Docs",
            "practice_url": "https://www.w3resource.com/python-exercises/numpy/index.php",
            "practice_title": "100 NumPy Exercises",
            "pdf_url": "https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html",
            "pdf_title": "Python Data Science Handbook - NumPy (FREE)",
            "tasks": [
                "Mathematical operations on arrays",
                "Linear algebra with NumPy",
                "Random number generation",
                "Matrix multiplication in Python",
            ],
        },
        20: {
            "day": 20,
            "phase": "DATA SCIENCE",
            "phase_color": "#2196F3",
            "topic": "Pandas: Series, DataFrame, Reading CSV",
            "video_title": "Complete Pandas Tutorial - Keith Galli",
            "video_url": "https://www.youtube.com/watch?v=vmEHCJofslg",
            "video_title2": "Pandas Tutorial - Corey Schafer",
            "video_url2": "https://www.youtube.com/watch?v=ZyhVh-qRZPA",
            "notes_url": "https://www.kaggle.com/learn/pandas",
            "notes_title": "Kaggle FREE Pandas Course",
            "practice_url": "https://www.kaggle.com/learn/pandas",
            "practice_title": "Kaggle Pandas Exercises",
            "pdf_url": "https://www.w3schools.com/python/pandas/default.asp",
            "pdf_title": "W3Schools - Pandas Tutorial",
            "tasks": [
                "Create Series and DataFrames",
                "Read CSV and Excel files",
                "Basic indexing and selection",
                "Kaggle Pandas Lesson 1-2",
            ],
        },
        21: {
            "day": 21,
            "phase": "DATA SCIENCE",
            "phase_color": "#2196F3",
            "topic": "Pandas: Filtering, Sorting, GroupBy, Aggregation",
            "video_title": "Pandas GroupBy - Corey Schafer",
            "video_url": "https://www.youtube.com/watch?v=txMdrV1naAQ",
            "video_title2": "Pandas Filtering Data - Corey Schafer",
            "video_url2": "https://www.youtube.com/watch?v=Lw2rlCxkroQ",
            "notes_url": "https://www.kaggle.com/learn/pandas",
            "notes_title": "Kaggle Pandas Course (Lesson 3-4)",
            "practice_url": "https://www.kaggle.com/learn/pandas",
            "practice_title": "Kaggle Pandas Exercises",
            "pdf_url": "https://pandas.pydata.org/docs/getting_started/intro_tutorials/index.html",
            "pdf_title": "Pandas Official Getting Started",
            "tasks": [
                "Filter rows with conditions",
                "Sort values and index",
                "GroupBy and aggregation",
                "20 Pandas queries on Titanic dataset",
            ],
        },
        22: {
            "day": 22,
            "phase": "DATA SCIENCE",
            "phase_color": "#2196F3",
            "topic": "Pandas: Merge, Join, Missing Data, Pivot Tables",
            "video_title": "Pandas Merge & Join - Corey Schafer",
            "video_url": "https://www.youtube.com/watch?v=h4hOPGo4UVU",
            "video_title2": "Handling Missing Data - Corey Schafer",
            "video_url2": "https://www.youtube.com/watch?v=KdmPHEnPJPs",
            "notes_url": "https://www.kaggle.com/learn/pandas",
            "notes_title": "Kaggle Pandas Course (Lesson 5)",
            "practice_url": "https://www.kaggle.com/learn/pandas",
            "practice_title": "Kaggle Pandas Final Exercises",
            "pdf_url": "https://www.geeksforgeeks.org/python-pandas-merging-joining-and-concatenating/",
            "pdf_title": "GFG - Pandas Merge & Join",
            "tasks": [
                "Merge, join, concat DataFrames",
                "Handle missing values (fillna, dropna)",
                "Pivot tables",
                "Clean a messy dataset",
            ],
        },
        23: {
            "day": 23,
            "phase": "DATA SCIENCE",
            "phase_color": "#2196F3",
            "topic": "Matplotlib: Line, Bar, Scatter, Histogram",
            "video_title": "Matplotlib Tutorial - Corey Schafer",
            "video_url": "https://www.youtube.com/watch?v=UO98lJQ3QGI",
            "video_title2": "Matplotlib Subplots - Corey Schafer",
            "video_url2": "https://www.youtube.com/watch?v=nKxLfUrkLE8",
            "notes_url": "https://www.kaggle.com/learn/data-visualization",
            "notes_title": "Kaggle FREE Data Visualization Course",
            "practice_url": "https://www.kaggle.com/learn/data-visualization",
            "practice_title": "Kaggle Visualization Exercises",
            "pdf_url": "https://www.w3schools.com/python/matplotlib_intro.asp",
            "pdf_title": "W3Schools - Matplotlib Tutorial",
            "tasks": [
                "Line plots, bar charts",
                "Scatter plots, histograms",
                "Subplots and customization",
                "Create 15 different plots",
            ],
        },
        24: {
            "day": 24,
            "phase": "DATA SCIENCE",
            "phase_color": "#2196F3",
            "topic": "Seaborn: Heatmaps, Pair plots, Box, Violin",
            "video_title": "Seaborn Tutorial - Full Course",
            "video_url": "https://www.youtube.com/watch?v=6GUZXDef2U0",
            "video_title2": "Data Visualization with Python",
            "video_url2": "https://www.youtube.com/watch?v=r-uOLxNrNk8",
            "notes_url": "https://www.kaggle.com/learn/data-visualization",
            "notes_title": "Kaggle Visualization Course",
            "practice_url": "https://www.kaggle.com/learn/data-visualization",
            "practice_title": "Kaggle Seaborn Exercises",
            "pdf_url": "https://seaborn.pydata.org/tutorial.html",
            "pdf_title": "Seaborn Official Tutorial",
            "tasks": [
                "Heatmaps and correlation maps",
                "Pair plots, box plots, violin plots",
                "Distribution plots",
                "Visualize Iris & Titanic datasets",
            ],
        },
        25: {
            "day": 25,
            "phase": "DATA SCIENCE",
            "phase_color": "#2196F3",
            "topic": "EDA Part 1: Exploratory Data Analysis Process",
            "video_title": "EDA Tutorial - Krish Naik",
            "video_url": "https://www.youtube.com/watch?v=fHFOANOb56g",
            "video_title2": "EDA with Pandas - FreeCodeCamp",
            "video_url2": "https://www.youtube.com/watch?v=r-uOLxNrNk8",
            "notes_url": "https://www.kaggle.com/learn/data-visualization",
            "notes_title": "Kaggle Data Viz (EDA section)",
            "practice_url": "https://www.kaggle.com/datasets/hm-land-registry/uk-housing-prices",
            "practice_title": "Kaggle Datasets for EDA",
            "pdf_url": "https://www.geeksforgeeks.org/what-is-exploratory-data-analysis/",
            "pdf_title": "GFG - EDA Complete Guide",
            "tasks": [
                "Understanding EDA process",
                "Univariate and bivariate analysis",
                "Correlation analysis",
                "Start EDA on a dataset",
            ],
        },
        26: {
            "day": 26,
            "phase": "DATA SCIENCE",
            "phase_color": "#2196F3",
            "topic": "EDA Part 2: Feature Analysis + Outlier Detection",
            "video_title": "Feature Engineering for ML",
            "video_url": "https://www.youtube.com/watch?v=fHFOANOb56g",
            "video_title2": "Outlier Detection Methods",
            "video_url2": "https://www.youtube.com/watch?v=rzR_cKnkD18",
            "notes_url": "https://www.geeksforgeeks.org/detect-and-remove-the-outliers-using-python/",
            "notes_title": "GFG - Outlier Detection",
            "practice_url": "https://www.kaggle.com/c/house-prices-advanced-regression-techniques",
            "practice_title": "Kaggle House Prices Dataset",
            "pdf_url": "https://www.geeksforgeeks.org/what-is-feature-engineering/",
            "pdf_title": "GFG - Feature Engineering",
            "tasks": [
                "Feature distributions analysis",
                "Outlier detection (IQR, Z-score)",
                "Correlation heatmaps",
                "Continue EDA notebook",
            ],
        },
        27: {
            "day": 27,
            "phase": "DATA SCIENCE",
            "phase_color": "#2196F3",
            "topic": "EDA PROJECT: Complete End-to-End EDA",
            "video_title": "Complete EDA Project Walkthrough",
            "video_url": "https://www.youtube.com/watch?v=fHFOANOb56g",
            "video_title2": "Kaggle EDA Notebooks (Read Top Ones)",
            "video_url2": "https://www.kaggle.com/c/house-prices-advanced-regression-techniques/code",
            "notes_url": "https://www.kaggle.com/c/house-prices-advanced-regression-techniques",
            "notes_title": "Kaggle House Prices Competition",
            "practice_url": "https://www.kaggle.com/c/house-prices-advanced-regression-techniques",
            "practice_title": "Submit EDA Notebook to Kaggle",
            "pdf_url": "https://jakevdp.github.io/PythonDataScienceHandbook/",
            "pdf_title": "Python Data Science Handbook (FREE)",
            "tasks": [
                "Complete full EDA on House Prices dataset",
                "Create beautiful visualizations",
                "Write insights and conclusions",
                "Push to GitHub with README",
            ],
        },

        # ========== PHASE 4: MACHINE LEARNING (Days 28-55) ==========
        28: {
            "day": 28,
            "phase": "MACHINE LEARNING",
            "phase_color": "#9C27B0",
            "topic": "What is ML? Types, Bias-Variance, Overfitting",
            "video_title": "Machine Learning for Everybody - FreeCodeCamp",
            "video_url": "https://www.youtube.com/watch?v=i_LwzRVP7bg",
            "video_title2": "Bias vs Variance - StatQuest",
            "video_url2": "https://www.youtube.com/watch?v=EuBBz3bI-aA",
            "notes_url": "https://developers.google.com/machine-learning/crash-course",
            "notes_title": "Google ML Crash Course (FREE)",
            "practice_url": "https://www.kaggle.com/learn/intro-to-machine-learning",
            "practice_title": "Kaggle Intro to ML (FREE)",
            "pdf_url": "https://www.geeksforgeeks.org/machine-learning/",
            "pdf_title": "GFG - Machine Learning Complete",
            "tasks": [
                "Supervised vs Unsupervised vs Reinforcement",
                "Bias-Variance tradeoff",
                "Overfitting vs Underfitting",
                "Draw mind maps of ML types",
            ],
        },
        29: {
            "day": 29,
            "phase": "MACHINE LEARNING",
            "phase_color": "#9C27B0",
            "topic": "Linear Regression: Cost Function, Gradient Descent",
            "video_title": "Linear Regression - StatQuest",
            "video_url": "https://www.youtube.com/watch?v=7ArmBVF2dCs",
            "video_title2": "Gradient Descent - StatQuest",
            "video_url2": "https://www.youtube.com/watch?v=sDv4f4s2SB8",
            "notes_url": "https://cs229.stanford.edu/main_notes.pdf",
            "notes_title": "Stanford CS229 Notes (FREE PDF)",
            "practice_url": "https://www.kaggle.com/learn/intro-to-machine-learning",
            "practice_title": "Kaggle ML Course (Lesson 1)",
            "pdf_url": "https://www.geeksforgeeks.org/ml-linear-regression/",
            "pdf_title": "GFG - Linear Regression Complete",
            "tasks": [
                "Understand cost function (MSE)",
                "Gradient descent algorithm",
                "Learning rate intuition",
                "Implement from SCRATCH in Python",
            ],
        },
        30: {
            "day": 30,
            "phase": "MACHINE LEARNING",
            "phase_color": "#9C27B0",
            "topic": "Linear Regression: Scikit-Learn, Train/Test Split",
            "video_title": "Sklearn Linear Regression Tutorial",
            "video_url": "https://www.youtube.com/watch?v=R15LjD8aCzc",
            "video_title2": "Train Test Split - Krish Naik",
            "video_url2": "https://www.youtube.com/watch?v=fwY9Qv96DJY",
            "notes_url": "https://scikit-learn.org/stable/modules/linear_model.html",
            "notes_title": "Scikit-Learn Official Docs",
            "practice_url": "https://www.kaggle.com/learn/intro-to-machine-learning",
            "practice_title": "Kaggle ML Exercises",
            "pdf_url": "https://www.geeksforgeeks.org/train-test-split/",
            "pdf_title": "GFG - Train Test Split",
            "tasks": [
                "sklearn LinearRegression",
                "train_test_split",
                "Predict house prices",
                "Evaluate with MSE and R2",
            ],
        },
    }

    # Days 31-55: ML Continued (generating programmatically for remaining days)
    ml_days = {
        31: ("Multiple + Polynomial Regression", "Multiple Regression - StatQuest", "https://www.youtube.com/watch?v=zITIFTsivN8", "Polynomial Regression Explained", "https://www.youtube.com/watch?v=QptI-vDle8Y"),
        32: ("Regularization: Ridge, Lasso, ElasticNet", "Ridge Regression - StatQuest", "https://www.youtube.com/watch?v=Q81RR3yKn30", "Lasso Regression - StatQuest", "https://www.youtube.com/watch?v=NGf0voTMlcs"),
        33: ("Regression Metrics: MSE, RMSE, MAE, R2", "R-Squared - StatQuest", "https://www.youtube.com/watch?v=2AQKmw14mHM", "Regression Metrics Explained", "https://www.youtube.com/watch?v=LbX4X71uoHo"),
        34: ("Logistic Regression", "Logistic Regression - StatQuest", "https://www.youtube.com/watch?v=yIYKR4sgzI8", "Logistic Regression Coefficients", "https://www.youtube.com/watch?v=vN5cNN2-HWE"),
        35: ("Classification Metrics: Confusion Matrix, ROC", "Confusion Matrix - StatQuest", "https://www.youtube.com/watch?v=Kdsp6soqA7o", "ROC and AUC - StatQuest", "https://www.youtube.com/watch?v=4jRBRDbJemM"),
        36: ("KNN (K-Nearest Neighbors)", "KNN - StatQuest", "https://www.youtube.com/watch?v=HVXime0nQeI", "KNN Implementation", "https://www.youtube.com/watch?v=4HKqjENq9OU"),
        37: ("Decision Trees", "Decision Trees - StatQuest", "https://www.youtube.com/watch?v=7VeUPuFGJHk", "Decision Tree Classification", "https://www.youtube.com/watch?v=_L39rN6gz7Y"),
        38: ("Random Forest", "Random Forest Part 1 - StatQuest", "https://www.youtube.com/watch?v=J4Wdy0Wc_xQ", "Random Forest Part 2 - StatQuest", "https://www.youtube.com/watch?v=sQ870aTKqiM"),
        39: ("SVM (Support Vector Machine)", "SVM Part 1 - StatQuest", "https://www.youtube.com/watch?v=efR1C6CvhmE", "SVM RBF Kernel - StatQuest", "https://www.youtube.com/watch?v=Qc5IyLW_hns"),
        40: ("Naive Bayes Classifier", "Naive Bayes - StatQuest", "https://www.youtube.com/watch?v=O2L2Uv9pdDA", "Gaussian Naive Bayes", "https://www.youtube.com/watch?v=H3EjCKtlVog"),
        41: ("Ensemble Methods: Bagging vs Boosting", "AdaBoost - StatQuest", "https://www.youtube.com/watch?v=LsK-xG1cLYA", "Bagging vs Boosting Explained", "https://www.youtube.com/watch?v=tjy0yL1rRRU"),
        42: ("Gradient Boosting + XGBoost", "Gradient Boost Part 1 - StatQuest", "https://www.youtube.com/watch?v=3CC4N4z3GJc", "XGBoost Part 1 - StatQuest", "https://www.youtube.com/watch?v=OtD8wVaFm6E"),
        43: ("LightGBM + CatBoost", "LightGBM Tutorial", "https://www.youtube.com/watch?v=n_ZMQj09S6w", "CatBoost Tutorial", "https://www.youtube.com/watch?v=8o0e-r0B5xQ"),
        44: ("K-Means Clustering", "K-Means - StatQuest", "https://www.youtube.com/watch?v=4b5d3muPQmA", "K-Means Implementation", "https://www.youtube.com/watch?v=EItlUEPCIzM"),
        45: ("Hierarchical Clustering + DBSCAN", "Hierarchical - StatQuest", "https://www.youtube.com/watch?v=7xHsRkOdVwo", "DBSCAN - StatQuest", "https://www.youtube.com/watch?v=RDZUdRSDOok"),
        46: ("PCA (Dimensionality Reduction)", "PCA - StatQuest", "https://www.youtube.com/watch?v=FgakZw6K1QQ", "PCA in Python - StatQuest", "https://www.youtube.com/watch?v=Lsbd2csBhNM"),
        47: ("Feature Engineering: Encoding, Scaling", "Feature Engineering Tutorial", "https://www.youtube.com/watch?v=6WDFfaYtN6s", "Kaggle Intermediate ML", "https://www.kaggle.com/learn/intermediate-machine-learning"),
        48: ("Feature Selection: RFE, Correlation", "Feature Selection Methods", "https://www.youtube.com/watch?v=xlBEEuYIWwY", "Feature Selection Tutorial", "https://www.youtube.com/watch?v=EqLBAmtKMnQ"),
        49: ("Cross Validation: K-Fold, Stratified", "Cross Validation - StatQuest", "https://www.youtube.com/watch?v=fSytzGwwBVw", "Cross Validation in Python", "https://www.youtube.com/watch?v=gJo0uNL-5Qw"),
        50: ("Hyperparameter Tuning: Grid, Random Search", "Hyperparameter Tuning", "https://www.youtube.com/watch?v=5nYqK-HaoKY", "GridSearchCV Tutorial", "https://www.youtube.com/watch?v=aKURsU_jnog"),
        51: ("Handling Imbalanced Data: SMOTE", "Imbalanced Data - Krish Naik", "https://www.youtube.com/watch?v=JnlM4yLFNuo", "SMOTE Tutorial", "https://www.youtube.com/watch?v=FheTK4hf0GM"),
        52: ("ML Pipelines in Scikit-Learn", "Sklearn Pipelines Tutorial", "https://www.youtube.com/watch?v=41HrPiMCwQQ", "ML Pipeline Complete Guide", "https://www.youtube.com/watch?v=w9IGkBfOoic"),
        53: ("ML PROJECT 1: Regression (House Prices)", "End-to-End ML Project", "https://www.youtube.com/watch?v=Wqmtf9SA_kk", "Kaggle House Prices Guide", "https://www.kaggle.com/c/house-prices-advanced-regression-techniques"),
        54: ("ML PROJECT 2: Classification (Heart Disease)", "Heart Disease Prediction", "https://www.youtube.com/watch?v=lDsz2vl7YEo", "Classification Project Tutorial", "https://www.youtube.com/watch?v=PVyHl3MnIXQ"),
        55: ("ML REVISION: Compare All Algorithms", "ML Algorithms Comparison", "https://www.youtube.com/watch?v=i_LwzRVP7bg", "When to Use Which Algorithm", "https://www.youtube.com/watch?v=E0Hmnixke20"),
    }

    for day, (topic, vt1, vu1, vt2, vu2) in ml_days.items():
        roadmap[day] = {
            "day": day,
            "phase": "MACHINE LEARNING",
            "phase_color": "#9C27B0",
            "topic": topic,
            "video_title": vt1,
            "video_url": vu1,
            "video_title2": vt2,
            "video_url2": vu2,
            "notes_url": "https://scikit-learn.org/stable/user_guide.html",
            "notes_title": "Scikit-Learn User Guide",
            "practice_url": "https://www.kaggle.com/learn/intermediate-machine-learning",
            "practice_title": "Kaggle Intermediate ML",
            "pdf_url": "https://github.com/afshinea/stanford-cs-229-machine-learning",
            "pdf_title": "Stanford CS229 ML Cheatsheets",
            "tasks": [
                f"Watch: {vt1}",
                f"Watch: {vt2}",
                "Implement in Python/Sklearn",
                "Practice on Kaggle dataset",
            ],
        }

    # ========== PHASE 5: DEEP LEARNING (Days 56-78) ==========
    dl_days = {
        56: ("Neural Network Intuition + Perceptron", "Neural Networks - 3Blue1Brown Ch1", "https://www.youtube.com/watch?v=aircAruvnKk", "MIT 6.S191 Lecture 1", "https://www.youtube.com/watch?v=ErnWZxJovaM"),
        57: ("Backpropagation", "Backprop - 3Blue1Brown Ch3", "https://www.youtube.com/watch?v=Ilg3gGewQ5U", "Backprop Calculus - 3B1B Ch4", "https://www.youtube.com/watch?v=tIeHLnjs5U8"),
        58: ("Loss Functions + Optimizers (SGD, Adam)", "Gradient Descent - StatQuest", "https://www.youtube.com/watch?v=sDv4f4s2SB8", "Adam Optimizer - StatQuest", "https://www.youtube.com/watch?v=MD2fYip6QUk"),
        59: ("TensorFlow + Keras Basics", "TensorFlow 2.0 Course - FreeCodeCamp", "https://www.youtube.com/watch?v=tPYj3fFJGjk", "TF Quickstart Tutorial", "https://www.tensorflow.org/tutorials/quickstart/beginner"),
        60: ("TensorFlow: Custom Layers, Callbacks", "TensorFlow Course Continued", "https://www.youtube.com/watch?v=tPYj3fFJGjk", "TF Keras Guide", "https://www.tensorflow.org/guide/keras"),
        61: ("PyTorch Basics: Tensors, Autograd", "PyTorch for DL - FreeCodeCamp", "https://www.youtube.com/watch?v=V_xro1bcAuQ", "PyTorch in 100 Seconds", "https://www.youtube.com/watch?v=ORMx45xqWkA"),
        62: ("DL Regularization: Dropout, BatchNorm", "Neural Networks - StatQuest", "https://www.youtube.com/watch?v=CqOfi41LfDw", "Dropout Explained", "https://www.youtube.com/watch?v=ARq74QuavAo"),
        63: ("Weight Init + Vanishing/Exploding Gradients", "Vanishing Gradient Problem", "https://www.youtube.com/watch?v=qhXZsFVxGKo", "Weight Initialization", "https://www.youtube.com/watch?v=s2coXdufOzE"),
        64: ("CNN Intuition: Convolution, Pooling, Filters", "MIT 6.S191 CNN Lecture", "https://www.youtube.com/watch?v=NmLK_WQBxB4", "CNN Explained Simply", "https://www.youtube.com/watch?v=YRhxdVk_sIs"),
        65: ("Build CNN in TensorFlow/Keras", "TF CNN Tutorial", "https://www.tensorflow.org/tutorials/images/cnn", "CNN for Beginners", "https://www.youtube.com/watch?v=HGwBXDKFk9I"),
        66: ("Build CNN in PyTorch", "PyTorch CNN Tutorial", "https://www.youtube.com/watch?v=pDdP0TFzsoQ", "PyTorch Image Classification", "https://www.youtube.com/watch?v=mozBidd2VsQ"),
        67: ("Famous CNNs: VGG, ResNet, Inception", "ResNet Explained", "https://www.youtube.com/watch?v=GWt6Fu05voI", "CNN Architectures Overview", "https://www.youtube.com/watch?v=dXB-KQYkzNU"),
        68: ("Transfer Learning: Pre-trained Models", "Transfer Learning - TensorFlow", "https://www.tensorflow.org/tutorials/images/transfer_learning", "Transfer Learning Tutorial", "https://www.youtube.com/watch?v=yofjFQddwHE"),
        69: ("Data Augmentation + Image Preprocessing", "TF Data Augmentation", "https://www.tensorflow.org/tutorials/images/data_augmentation", "Data Augmentation Techniques", "https://www.youtube.com/watch?v=mTVf7BN7S8w"),
        70: ("Object Detection: YOLO Basics", "YOLO Explained", "https://www.youtube.com/watch?v=9s_FpMpdYW8", "YOLOv8 Tutorial", "https://www.youtube.com/watch?v=Z-65nqxUGBY"),
        71: ("CNN PROJECT: Image Classifier", "Image Classification Project", "https://www.youtube.com/watch?v=jztwpsIzEGc", "Plant Disease Detection", "https://www.youtube.com/watch?v=FnhRtQ6AKr4"),
        72: ("RNN Basics: Sequential Data", "RNN - StatQuest", "https://www.youtube.com/watch?v=AsNTP8Kwu80", "MIT 6.S191 RNN Lecture", "https://www.youtube.com/watch?v=ySEx_Bqxvvo"),
        73: ("LSTM + GRU: Gates and Architecture", "LSTM - StatQuest", "https://www.youtube.com/watch?v=YCzL96nL7j0", "GRU Explained", "https://www.youtube.com/watch?v=8HyCNIVRbSU"),
        74: ("Word Embeddings: Word2Vec, GloVe", "Word Embeddings - StatQuest", "https://www.youtube.com/watch?v=viZrOnJclY0", "Word2Vec - StatQuest", "https://www.youtube.com/watch?v=INHhqNow4cA"),
        75: ("Text Classification with LSTM", "Text Classification - TensorFlow", "https://www.tensorflow.org/text/tutorials/text_classification_rnn", "Sentiment Analysis LSTM", "https://www.youtube.com/watch?v=c0isaztveHs"),
        76: ("Time Series Forecasting with LSTM", "Time Series - TensorFlow", "https://www.tensorflow.org/tutorials/structured_data/time_series", "Stock Prediction LSTM", "https://www.youtube.com/watch?v=CbTU92pbDKw"),
        77: ("Autoencoders + VAE", "Autoencoders Explained", "https://www.youtube.com/watch?v=9zKuYvjFFS8", "Build Autoencoder", "https://www.youtube.com/watch?v=fcvYpzHmhvA"),
        78: ("GANs: Generator + Discriminator", "GANs Explained", "https://www.youtube.com/watch?v=8L11aMN5KY8", "Build Simple GAN", "https://www.youtube.com/watch?v=OljTVls23aI"),
    }

    for day, (topic, vt1, vu1, vt2, vu2) in dl_days.items():
        roadmap[day] = {
            "day": day,
            "phase": "DEEP LEARNING",
            "phase_color": "#F44336",
            "topic": topic,
            "video_title": vt1,
            "video_url": vu1,
            "video_title2": vt2,
            "video_url2": vu2,
            "notes_url": "https://d2l.ai/",
            "notes_title": "Dive into Deep Learning (FREE Book)",
            "practice_url": "https://www.tensorflow.org/tutorials",
            "practice_title": "TensorFlow Official Tutorials",
            "pdf_url": "https://cs231n.github.io/",
            "pdf_title": "Stanford CS231n Notes (FREE)",
            "tasks": [
                f"Watch: {vt1}",
                f"Watch: {vt2}",
                "Implement in TensorFlow/PyTorch",
                "Train model on Google Colab",
            ],
        }

    # ========== PHASE 6: NLP & TRANSFORMERS (Days 79-90) ==========
    nlp_days = {
        79: ("NLP Basics: Tokenization, NLTK, SpaCy", "NLP with Python - FreeCodeCamp", "https://www.youtube.com/watch?v=fOvTtapxa9c", "NLTK Tutorial", "https://www.youtube.com/watch?v=X2vAabgKiuM"),
        80: ("TF-IDF + Text Classification with ML", "TF-IDF Explained", "https://www.youtube.com/watch?v=D2V1okCEsiE", "Text Classification sklearn", "https://www.youtube.com/watch?v=M7SWr5xObkA"),
        81: ("Attention Mechanism", "Attention - 3Blue1Brown", "https://www.youtube.com/watch?v=eMlx5fFNoYc", "Attention - StatQuest", "https://www.youtube.com/watch?v=PSs6nxngL6k"),
        82: ("Transformer Architecture", "Transformer - StatQuest", "https://www.youtube.com/watch?v=zxQyTK8quyY", "Illustrated Transformer (Blog)", "https://jalammar.github.io/illustrated-transformer/"),
        83: ("Build GPT from Scratch", "Let's Build GPT - Andrej Karpathy", "https://www.youtube.com/watch?v=kCc8FmEb1nY", "GPT from Scratch Part 2", "https://www.youtube.com/watch?v=l8pRSuU81PU"),
        84: ("BERT: Theory + Hugging Face", "Illustrated BERT (Blog)", "https://jalammar.github.io/illustrated-bert/", "Hugging Face Course Ch1", "https://huggingface.co/learn/nlp-course/chapter1"),
        85: ("Hugging Face Transformers Library", "Hugging Face Course Ch2", "https://huggingface.co/learn/nlp-course/chapter2", "HF Transformers Tutorial", "https://www.youtube.com/watch?v=QEaBAZQCtwE"),
        86: ("Fine-tuning BERT for Classification", "Hugging Face Course Ch3", "https://huggingface.co/learn/nlp-course/chapter3", "Fine-tune BERT Tutorial", "https://www.youtube.com/watch?v=PYeh-97IAoE"),
        87: ("GPT + LLMs + Prompt Engineering", "State of GPT - Andrej Karpathy", "https://www.youtube.com/watch?v=bZQun8Y4L2A", "Prompt Engineering Guide", "https://www.youtube.com/watch?v=_ZvnD96BsQo"),
        88: ("LangChain Basics: Chains, Prompts", "LangChain Course - FreeCodeCamp", "https://www.youtube.com/watch?v=lG7Uxts9SXs", "LangChain Tutorial", "https://www.youtube.com/watch?v=aywZrzNaKjs"),
        89: ("RAG: Retrieval Augmented Generation", "RAG Tutorial", "https://www.youtube.com/watch?v=tcqEUSNCn8I", "Build RAG App", "https://www.youtube.com/watch?v=BrsocJb-fAo"),
        90: ("NLP PROJECT: Sentiment Analyzer / Chatbot", "Sentiment Analysis Project", "https://www.youtube.com/watch?v=szczpgOEdXs", "Build AI Chatbot", "https://www.youtube.com/watch?v=RpWeNzfSUHw"),
    }

    for day, (topic, vt1, vu1, vt2, vu2) in nlp_days.items():
        roadmap[day] = {
            "day": day,
            "phase": "NLP & TRANSFORMERS",
            "phase_color": "#E91E63",
            "topic": topic,
            "video_title": vt1,
            "video_url": vu1,
            "video_title2": vt2,
            "video_url2": vu2,
            "notes_url": "https://huggingface.co/learn/nlp-course",
            "notes_title": "Hugging Face NLP Course (FREE)",
            "practice_url": "https://huggingface.co/models",
            "practice_title": "Hugging Face Models Hub",
            "pdf_url": "https://jalammar.github.io/",
            "pdf_title": "Jay Alammar Illustrated Guides (FREE)",
            "tasks": [
                f"Watch: {vt1}",
                f"Watch: {vt2}",
                "Implement / Fine-tune models",
                "Build NLP application",
            ],
        }

    # ========== PHASE 7: DEPLOYMENT (Days 91-100) ==========
    deploy_days = {
        91: ("Flask API Development", "Flask Tutorial - FreeCodeCamp", "https://www.youtube.com/watch?v=Z1RJmh_OqeA", "Deploy ML Model Flask", "https://www.youtube.com/watch?v=mrExsjcvF4o"),
        92: ("Streamlit Web Apps", "Streamlit Crash Course", "https://www.youtube.com/watch?v=Ebb4gUI2IpQ", "Build ML App Streamlit", "https://www.youtube.com/watch?v=Klqn--Mu2pE"),
        93: ("Model Serialization: Pickle, Joblib, ONNX", "Save & Load ML Models", "https://www.youtube.com/watch?v=KfnhNlD8WZI", "Model Deployment Guide", "https://www.youtube.com/watch?v=bjsJOl8gz5k"),
        94: ("Docker Basics + HuggingFace Spaces", "Docker Tutorial - FreeCodeCamp", "https://www.youtube.com/watch?v=fqMOX6JJhGo", "Deploy to HF Spaces", "https://www.youtube.com/watch?v=_j7JEDWuqLE"),
        95: ("CAPSTONE 1: End-to-End ML Project (Start)", "End-to-End ML Project", "https://www.youtube.com/watch?v=Wqmtf9SA_kk", "ML System Design", "https://www.youtube.com/watch?v=pYVScuY-GPk"),
        96: ("CAPSTONE 1: Deploy on Streamlit (Complete)", "Streamlit Deployment", "https://www.youtube.com/watch?v=Klqn--Mu2pE", "Write Great README", "https://www.youtube.com/watch?v=E6NO0rgFub4"),
        97: ("CAPSTONE 2: Deep Learning Project (Start)", "CNN Project Complete", "https://www.youtube.com/watch?v=jztwpsIzEGc", "Image Classifier App", "https://www.youtube.com/watch?v=WFr2WgN9_xE"),
        98: ("CAPSTONE 2: Deploy DL Model (Complete)", "Deploy DL Model", "https://www.youtube.com/watch?v=bjsJOl8gz5k", "Gradio App Tutorial", "https://www.youtube.com/watch?v=RiCQzBluTxU"),
        99: ("CAPSTONE 3: NLP Project", "NLP Project Complete", "https://www.youtube.com/watch?v=szczpgOEdXs", "Build AI App", "https://www.youtube.com/watch?v=RpWeNzfSUHw"),
        100: ("DAY 100: Portfolio + LinkedIn + CELEBRATE!", "Build Dev Portfolio", "https://www.youtube.com/watch?v=oTIJunBa6MA", "LinkedIn for Developers", "https://www.youtube.com/watch?v=SG5Sb5WTV_g"),
    }

    for day, (topic, vt1, vu1, vt2, vu2) in deploy_days.items():
        roadmap[day] = {
            "day": day,
            "phase": "DEPLOYMENT & PROJECTS",
            "phase_color": "#607D8B",
            "topic": topic,
            "video_title": vt1,
            "video_url": vu1,
            "video_title2": vt2,
            "video_url2": vu2,
            "notes_url": "https://docs.streamlit.io/",
            "notes_title": "Streamlit Documentation",
            "practice_url": "https://huggingface.co/spaces",
            "practice_title": "Deploy on HuggingFace Spaces",
            "pdf_url": "https://www.geeksforgeeks.org/deploy-machine-learning-model-using-flask/",
            "pdf_title": "GFG - ML Deployment Guide",
            "tasks": [
                f"Watch: {vt1}",
                f"Watch: {vt2}",
                "Build and deploy project",
                "Push to GitHub with README",
            ],
        }

    return roadmap